application: stoked-depth-92800
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css 

- url: /js
  static_dir: js   

- url: /images
  static_dir: images
  mime_type: images/png

- url: .*
  script: templates.app



libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest  